apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: flask-mongo-namespace
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: rootuser
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
  MONGO_USERNAME: rootuser
  MONGO_PASSWORD: rootpassword
